# File Name: spr_salt_cavern_hydraulics.py
# Location: /src/modules/
# Subsystem: Strategic Petroleum Reserve (SPR) Brine Displacement
# Copyright (c) 2026 Revolutionary Technology

import time
import math
import numpy as np
from numba import njit, prange
from typing import Dict, Any, List

@njit(parallel=True, cache=True, fastmath=True)
def parallel_calculate_brine_displacement(brine_injection_m3_s: np.ndarray, cavern_depth_m: np.ndarray) -> np.ndarray:
    """Calculates bottom-hole pressure (MPa) generated by brine injection to displace crude oil."""
    total_caverns = brine_injection_m3_s.shape[0]
    pressures_mpa = np.zeros(total_caverns, dtype=np.float64)
    
    # Saturated brine density ~1200 kg/m3. Crude oil ~850 kg/m3. Gravity 9.81 m/s^2.
    gravity = 9.81
    brine_density = 1200.0 
    
    for i in prange(total_caverns):
        # Hydrostatic pressure of the brine column
        hydrostatic_p_pa = brine_density * gravity * cavern_depth_m[i]
        
        # Dynamic injection pressure (friction proxy based on flow rate)
        dynamic_p_pa = brine_injection_m3_s[i] * 45000.0 
        
        total_p_pa = hydrostatic_p_pa + dynamic_p_pa
        pressures_mpa[i] = total_p_pa / 1000000.0 # Convert to Megapascals
        
    return pressures_mpa

class StrategicPetroleumReserveCore:
    def __init__(self):
        self.salt_fracture_gradient_mpa = 22.0 # Pressure at which the salt dome cracks, losing the oil

    def execute_emergency_drawdown(self, cavern_ids: List[str], depths_meters: List[float], injection_rates_m3_s: List[float]) -> dict:
        print(f"\n[ENERGY SECURITY] Initiating Strategic Petroleum Reserve (SPR) brine displacement...")
        start_time = time.time()
        
        inj_arr = np.array(injection_rates_m3_s, dtype=np.float64)
        depth_arr = np.array(depths_meters, dtype=np.float64)
        
        # Execute JIT Math
        bottom_hole_pressures_mpa = parallel_calculate_brine_displacement(inj_arr, depth_arr)
        
        total_crude_yield_m3_s = 0.0
        fracture_warnings = []
        
        for i in range(len(cavern_ids)):
            p_mpa = bottom_hole_pressures_mpa[i]
            if p_mpa >= self.salt_fracture_gradient_mpa:
                fracture_warnings.append({
                    "cavern": cavern_ids[i],
                    "bottom_hole_pressure_mpa": round(p_mpa, 2),
                    "action": "THROTTLE_BRINE_INJECTION_PUMPS"
                })
            else:
                # 1 m^3 of brine injected = roughly 1 m^3 of crude displaced
                total_crude_yield_m3_s += injection_rates_m3_s[i]

        # Convert m^3/s to Barrels per Day (1 m^3 = 6.2898 barrels, * 86400 seconds)
        barrels_per_day = total_crude_yield_m3_s * 6.2898 * 86400.0
        
        execution_ms = (time.time() - start_time) * 1000.0
        
        status = "DRAWDOWN_NOMINAL" if not fracture_warnings else "CAVERN_FRACTURE_WARNING"

        return {
            "spr_status": status,
            "caverns_active": len(cavern_ids),
            "crude_oil_yield_bpd": int(barrels_per_day),
            "geological_faults": fracture_warnings,
            "execution_time_ms": round(execution_ms, 5)
        }

if __name__ == "__main__":
    spr = StrategicPetroleumReserveCore()
    # Mocking massive salt domes in Louisiana/Texas. Cavern 3 is being pumped too aggressively at deep depths.
    print("TESTING SPR HYDRAULIC CORE:\n", spr.execute_emergency_drawdown(
        ["BRYAN-MOUND-1", "WEST-HACKBERRY-2", "BAYOU-CHOCTAW-3"], 
        [1000.0, 1200.0, 1800.0], # Depths
        [1.5, 2.0, 4.5]           # Brine injection m^3/s
    ))
